/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import battlesimulator.Military.Army.ArmyStats;
import java.awt.Color;

/**
 *
 * @author Arlo
 */
public class ArmyStatsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ArmyStats
     */
    public ArmyStatsPanel(Color armyColor) {
        initComponents();
        lblArmyHead.setForeground(armyColor);
        lblGeneralHead.setForeground(armyColor);
        lblTroopsHead.setForeground(armyColor);
        lblUnitsHead.setForeground(armyColor);
        lblScoreHead.setForeground(armyColor);
    }

    public void setStats(ArmyStats stats) {

        lblActiveTroops.setText("" + stats.getTotalActiveTroops());
        lblAllegiance.setText(stats.getAllegiance());
        lblGeneral.setText(stats.getGeneral().getName());
        lblUnits.setText("" + stats.getNumUnits());
        lblArmyScore.setText("" + stats.getArmyScore());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblArmyHead = new javax.swing.JLabel();
        lblGeneralHead = new javax.swing.JLabel();
        lblUnitsHead = new javax.swing.JLabel();
        lblTroopsHead = new javax.swing.JLabel();
        lblAllegiance = new javax.swing.JLabel();
        lblGeneral = new javax.swing.JLabel();
        lblUnits = new javax.swing.JLabel();
        lblActiveTroops = new javax.swing.JLabel();
        lblScoreHead = new javax.swing.JLabel();
        lblArmyScore = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblArmyHead.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArmyHead.setText("Army:");
        lblArmyHead.setToolTipText("");

        lblGeneralHead.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGeneralHead.setText("General:");
        lblGeneralHead.setToolTipText("");

        lblUnitsHead.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUnitsHead.setText("Units:");
        lblUnitsHead.setToolTipText("");

        lblTroopsHead.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTroopsHead.setText("Active Toops:");
        lblTroopsHead.setToolTipText("");

        lblAllegiance.setText("---");

        lblGeneral.setText("---");

        lblUnits.setText("---");

        lblActiveTroops.setText("---");

        lblScoreHead.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblScoreHead.setText("Army Score:");
        lblScoreHead.setToolTipText("");

        lblArmyScore.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArmyHead)
                            .addComponent(lblGeneralHead)
                            .addComponent(lblUnitsHead)
                            .addComponent(lblTroopsHead))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAllegiance, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(lblGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblActiveTroops, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblScoreHead)
                        .addGap(18, 18, 18)
                        .addComponent(lblArmyScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArmyHead)
                    .addComponent(lblAllegiance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneralHead)
                    .addComponent(lblGeneral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitsHead)
                    .addComponent(lblUnits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTroopsHead)
                    .addComponent(lblActiveTroops))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScoreHead)
                    .addComponent(lblArmyScore))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblActiveTroops;
    private javax.swing.JLabel lblAllegiance;
    private javax.swing.JLabel lblArmyHead;
    private javax.swing.JLabel lblArmyScore;
    private javax.swing.JLabel lblGeneral;
    private javax.swing.JLabel lblGeneralHead;
    private javax.swing.JLabel lblScoreHead;
    private javax.swing.JLabel lblTroopsHead;
    private javax.swing.JLabel lblUnits;
    private javax.swing.JLabel lblUnitsHead;
    // End of variables declaration//GEN-END:variables
}
