/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SimBuilderTools;

import Strategy.StrategyService;
import battlesimulator.Military.General;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JRadioButton;

/**
 *
 * @author Arlo
 */
public class CreateGeneral extends SimBuilderTools.AbstractCreationPanel<General>
{

    General general;
    ArrayList<JRadioButton> strategyButtons;

    /**
     * Creates new form GeneralPanel
     */
    public CreateGeneral()
    {
        super();
        strategyButtons = new ArrayList<>();
        initComponents();
        StrategyService service = StrategyService.getInstance();
        for (String stratName : service.getStratsNames())
        {
            JRadioButton stratButton = new JRadioButton(stratName);
            this.bntGroupStrats.add(stratButton);
            this.strategyButtons.add(stratButton);
            this.stratButtonsPanel.add(stratButton);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bntGroupStrats = new javax.swing.ButtonGroup();
        fillNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fldName = new javax.swing.JTextField();
        stratButtonsPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Name:");

        fldName.setText("general");

        javax.swing.GroupLayout fillNamePanelLayout = new javax.swing.GroupLayout(fillNamePanel);
        fillNamePanel.setLayout(fillNamePanelLayout);
        fillNamePanelLayout.setHorizontalGroup(
            fillNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        fillNamePanelLayout.setVerticalGroup(
            fillNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fillNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(fillNamePanel, java.awt.BorderLayout.NORTH);

        stratButtonsPanel.setMinimumSize(new java.awt.Dimension(182, 182));
        stratButtonsPanel.setPreferredSize(new java.awt.Dimension(182, 182));
        stratButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(stratButtonsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntGroupStrats;
    private javax.swing.JPanel fillNamePanel;
    private javax.swing.JTextField fldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel stratButtonsPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Save()
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void Load()
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public boolean Validate()
    {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public General buildObject()
    {
        if (general == null)
        {
            this.general = new General("", this.fldName.getText());
        } else
        {
            this.general.setName(this.fldName.getText());
        }
        String stratName = "";
        for (JRadioButton button : this.strategyButtons)
        {
            if (button.isSelected())
            {
                stratName = button.getText();
            }
        }
        general.setPreferedStrategy(stratName);
        //this.general.setPreferedStrategy(this.);
        return general;
    }

    @Override
    public void setObject(General object)
    {
        if (object == null)
        {
            this.general = new General("", "name");
        } else
        {

            this.general = object;
        }
        this.fldName.setText(this.general.getName());
    }
}
