/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SimBuilderTools;

import battlesimulator.Geography.StartingPosition;
import java.awt.Point;

/**
 *
 * @author Arlo
 */
public class CreateStartingPosition extends javax.swing.JPanel {
CreateBattlefield createBattlefield;
    /**
     * Creates new form SetStartingPosition
     */
    public CreateStartingPosition(CreateBattlefield createBattlefield) {
        initComponents();
        this.createBattlefield = createBattlefield;
    }
    
        /**
     * Creates new form SetStartingPosition
     */
    public CreateStartingPosition(CreateBattlefield createBattlefield, String name, Point seedPoint) {
       this(createBattlefield);
       
       this.fieldName.setText(name);
       this.setCoordinates1.setPoint(seedPoint);
    }
    
    public SetCoordinates getCoordinates()
    {
        return this.setCoordinates1;
    }
    
    public SetDimensions getDimensions()
    {
        return this.setDimensions1;
    }
    
    public String getFieldName()
    {
        return this.fieldName.getText();
    }
    
    public void setPosition(StartingPosition position, String name)
    {
        this.fieldName.setText(name);
        this.setCoordinates1.setPoint(position.getCornerPoint());
        this.setDimensions1.setDimension(position.getShape().getBounds().getSize());
    }
    
    public String getPositionName()
    {
        return this.fieldName.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        setCoordinates1 = new SimBuilderTools.SetCoordinates();
        setDimensions1 = new SimBuilderTools.SetDimensions();
        btnRemove = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(272, 80));
        setMinimumSize(new java.awt.Dimension(272, 80));

        jLabel1.setText("Name");
        jLabel1.setToolTipText("");

        fieldName.setText("startingPos");
        fieldName.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                fieldNameKeyReleased(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setDimensions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setCoordinates1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(setCoordinates1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(setDimensions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnRemove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        this.createBattlefield.removeStartingPostion(this);
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void fieldNameKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fieldNameKeyReleased
    {//GEN-HEADEREND:event_fieldNameKeyReleased
        this.createBattlefield.notifyListeners();
    }//GEN-LAST:event_fieldNameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    private SimBuilderTools.SetCoordinates setCoordinates1;
    private SimBuilderTools.SetDimensions setDimensions1;
    // End of variables declaration//GEN-END:variables
}
